//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/JaspersPlayerController/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""UIMenu"",
            ""id"": ""26041262-b8e5-48be-ba93-0490080be55e"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""17c692cd-19d8-455a-adf2-57bcb113fe19"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""2bf88ee9-b239-44a9-b886-3ec7cf7e1750"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""d6e6b4f4-bb1d-462a-aebf-af6afbe3a3a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4f16e6e4-7e4c-4225-b285-5d9e407a9431"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""47e74adb-ed63-4a14-b8b9-86d345254457"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""57155ef3-d5e6-4aed-8b8b-1811f437ddfd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""Button"",
                    ""id"": ""70c1c49b-a02f-451d-a240-de75f21047e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""ac89e2ec-b502-429f-a433-84a788e50939"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""c84099fc-c69c-44fd-b1e7-0a48e170cd8c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""952dea54-ff16-4760-a8a1-570d4850a8c9"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7d32d111-2bdf-45d3-8035-4c55da8d5a12"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d0b78082-4e27-48cb-9da6-7d10e938fcc1"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ef9f215b-ead1-41ac-a79f-88c889f468e5"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6ad6f817-0677-4d4c-bf64-eb4ccdd0d42d"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""64cef4d5-ed2e-43fc-8400-76e98dc637aa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f05dd894-7513-41b6-b757-ef20c4969592"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""224de710-7b71-40bd-a5a2-79fa4560d750"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d366375a-9597-418a-9601-f5a1d921e2ef"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0b70628e-b93d-4ce6-b141-47c3e43d36a2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1f9ef611-7de8-4fb8-a629-5c6202528887"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4d1b3f41-fa94-4d4d-92c4-e76b060f87ef"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""843e43e0-44ea-4752-ae47-36fc0e74bf3e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d31df5cc-f4b4-4c14-982c-ec0cb67527fe"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e070438-c9cf-427f-9409-373c31e7badf"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43f5f607-3a1f-4f1f-8ec5-a8ba5135e600"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ce369d0-a55c-4f41-b40c-e74876190dff"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8702a9e1-2e50-4c86-a27b-9d991b9575d9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47aa7335-18fa-4a26-b331-db86df8ba284"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99cb76bd-60c0-4df6-8dae-db0c1e8f5b0e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""905ef247-442a-4800-96b8-6cb3ced1d169"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerOnFoot"",
            ""id"": ""d81bc04c-ba7e-4369-9818-23baf9b52ef0"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""35ea2230-fbfc-41e4-b2fa-012a5bc54c74"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a4b0d8f2-cbce-4842-abca-029603c816b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""QuickhackMenuActive"",
                    ""type"": ""Button"",
                    ""id"": ""0246b916-0570-4f04-bf6c-3faddb0fced2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickhackMenuNavigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""68a81363-c691-4d72-8ac5-309cc9f3b327"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickhackMenuSelect"",
                    ""type"": ""Button"",
                    ""id"": ""6a5206e1-9944-4f14-a58a-7dd6eaf0f180"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickhackMenuCancel"",
                    ""type"": ""Button"",
                    ""id"": ""71ea0513-e07a-4307-84af-b27ba5e90544"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c9eefa3-c4b9-47e1-8f3b-cd3acae487ae"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a8d1e3cc-12d4-4362-a34d-319a08eb3a8e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8af791e7-20d9-48a4-b260-a7e862516db9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1e38592d-e888-4994-b002-230e2935bd83"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b016641d-84e5-409d-8a18-b65f9657ec55"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b3fd66c4-684e-47cd-87b1-ab0f75427b4b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ec478899-662f-44e4-95f5-c3c27e2bc8cb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32ab4a61-d881-4aba-b477-775c5e161722"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c614b1b-94de-4cf6-a2de-abf52d29316e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""QuickhackMenuActive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97bdada9-5205-4f0c-b0f2-1aa39560ce32"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""QuickhackMenuNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47279163-3b0d-4ddf-abb2-4c2b75584e4b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""QuickhackMenuSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4717653b-8199-482d-b72f-0628bfe9a82b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse-Keyboard"",
                    ""action"": ""QuickhackMenuCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse-Keyboard"",
            ""bindingGroup"": ""Mouse-Keyboard"",
            ""devices"": []
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
        // UIMenu
        m_UIMenu = asset.FindActionMap("UIMenu", throwIfNotFound: true);
        m_UIMenu_Navigate = m_UIMenu.FindAction("Navigate", throwIfNotFound: true);
        m_UIMenu_Submit = m_UIMenu.FindAction("Submit", throwIfNotFound: true);
        m_UIMenu_Cancel = m_UIMenu.FindAction("Cancel", throwIfNotFound: true);
        m_UIMenu_Point = m_UIMenu.FindAction("Point", throwIfNotFound: true);
        m_UIMenu_Click = m_UIMenu.FindAction("Click", throwIfNotFound: true);
        m_UIMenu_ScrollWheel = m_UIMenu.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UIMenu_MiddleClick = m_UIMenu.FindAction("MiddleClick", throwIfNotFound: true);
        m_UIMenu_RightClick = m_UIMenu.FindAction("RightClick", throwIfNotFound: true);
        // PlayerOnFoot
        m_PlayerOnFoot = asset.FindActionMap("PlayerOnFoot", throwIfNotFound: true);
        m_PlayerOnFoot_Move = m_PlayerOnFoot.FindAction("Move", throwIfNotFound: true);
        m_PlayerOnFoot_Look = m_PlayerOnFoot.FindAction("Look", throwIfNotFound: true);
        m_PlayerOnFoot_QuickhackMenuActive = m_PlayerOnFoot.FindAction("QuickhackMenuActive", throwIfNotFound: true);
        m_PlayerOnFoot_QuickhackMenuNavigate = m_PlayerOnFoot.FindAction("QuickhackMenuNavigate", throwIfNotFound: true);
        m_PlayerOnFoot_QuickhackMenuSelect = m_PlayerOnFoot.FindAction("QuickhackMenuSelect", throwIfNotFound: true);
        m_PlayerOnFoot_QuickhackMenuCancel = m_PlayerOnFoot.FindAction("QuickhackMenuCancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UIMenu
    private readonly InputActionMap m_UIMenu;
    private IUIMenuActions m_UIMenuActionsCallbackInterface;
    private readonly InputAction m_UIMenu_Navigate;
    private readonly InputAction m_UIMenu_Submit;
    private readonly InputAction m_UIMenu_Cancel;
    private readonly InputAction m_UIMenu_Point;
    private readonly InputAction m_UIMenu_Click;
    private readonly InputAction m_UIMenu_ScrollWheel;
    private readonly InputAction m_UIMenu_MiddleClick;
    private readonly InputAction m_UIMenu_RightClick;
    public struct UIMenuActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIMenuActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UIMenu_Navigate;
        public InputAction @Submit => m_Wrapper.m_UIMenu_Submit;
        public InputAction @Cancel => m_Wrapper.m_UIMenu_Cancel;
        public InputAction @Point => m_Wrapper.m_UIMenu_Point;
        public InputAction @Click => m_Wrapper.m_UIMenu_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UIMenu_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UIMenu_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UIMenu_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_UIMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIMenuActions set) { return set.Get(); }
        public void SetCallbacks(IUIMenuActions instance)
        {
            if (m_Wrapper.m_UIMenuActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIMenuActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_UIMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public UIMenuActions @UIMenu => new UIMenuActions(this);

    // PlayerOnFoot
    private readonly InputActionMap m_PlayerOnFoot;
    private IPlayerOnFootActions m_PlayerOnFootActionsCallbackInterface;
    private readonly InputAction m_PlayerOnFoot_Move;
    private readonly InputAction m_PlayerOnFoot_Look;
    private readonly InputAction m_PlayerOnFoot_QuickhackMenuActive;
    private readonly InputAction m_PlayerOnFoot_QuickhackMenuNavigate;
    private readonly InputAction m_PlayerOnFoot_QuickhackMenuSelect;
    private readonly InputAction m_PlayerOnFoot_QuickhackMenuCancel;
    public struct PlayerOnFootActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerOnFootActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerOnFoot_Move;
        public InputAction @Look => m_Wrapper.m_PlayerOnFoot_Look;
        public InputAction @QuickhackMenuActive => m_Wrapper.m_PlayerOnFoot_QuickhackMenuActive;
        public InputAction @QuickhackMenuNavigate => m_Wrapper.m_PlayerOnFoot_QuickhackMenuNavigate;
        public InputAction @QuickhackMenuSelect => m_Wrapper.m_PlayerOnFoot_QuickhackMenuSelect;
        public InputAction @QuickhackMenuCancel => m_Wrapper.m_PlayerOnFoot_QuickhackMenuCancel;
        public InputActionMap Get() { return m_Wrapper.m_PlayerOnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerOnFootActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerOnFootActions instance)
        {
            if (m_Wrapper.m_PlayerOnFootActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnLook;
                @QuickhackMenuActive.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuActive;
                @QuickhackMenuActive.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuActive;
                @QuickhackMenuActive.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuActive;
                @QuickhackMenuNavigate.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuNavigate;
                @QuickhackMenuNavigate.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuNavigate;
                @QuickhackMenuNavigate.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuNavigate;
                @QuickhackMenuSelect.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuSelect;
                @QuickhackMenuSelect.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuSelect;
                @QuickhackMenuSelect.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuSelect;
                @QuickhackMenuCancel.started -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuCancel;
                @QuickhackMenuCancel.performed -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuCancel;
                @QuickhackMenuCancel.canceled -= m_Wrapper.m_PlayerOnFootActionsCallbackInterface.OnQuickhackMenuCancel;
            }
            m_Wrapper.m_PlayerOnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @QuickhackMenuActive.started += instance.OnQuickhackMenuActive;
                @QuickhackMenuActive.performed += instance.OnQuickhackMenuActive;
                @QuickhackMenuActive.canceled += instance.OnQuickhackMenuActive;
                @QuickhackMenuNavigate.started += instance.OnQuickhackMenuNavigate;
                @QuickhackMenuNavigate.performed += instance.OnQuickhackMenuNavigate;
                @QuickhackMenuNavigate.canceled += instance.OnQuickhackMenuNavigate;
                @QuickhackMenuSelect.started += instance.OnQuickhackMenuSelect;
                @QuickhackMenuSelect.performed += instance.OnQuickhackMenuSelect;
                @QuickhackMenuSelect.canceled += instance.OnQuickhackMenuSelect;
                @QuickhackMenuCancel.started += instance.OnQuickhackMenuCancel;
                @QuickhackMenuCancel.performed += instance.OnQuickhackMenuCancel;
                @QuickhackMenuCancel.canceled += instance.OnQuickhackMenuCancel;
            }
        }
    }
    public PlayerOnFootActions @PlayerOnFoot => new PlayerOnFootActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse-Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IUIMenuActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
    public interface IPlayerOnFootActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnQuickhackMenuActive(InputAction.CallbackContext context);
        void OnQuickhackMenuNavigate(InputAction.CallbackContext context);
        void OnQuickhackMenuSelect(InputAction.CallbackContext context);
        void OnQuickhackMenuCancel(InputAction.CallbackContext context);
    }
}
